
server:
  port: 8001

spring.jpa:
  database: MYSQL
  hibernate.ddl-auto: create-drop
  show-sql: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registrydb
    username: root
    password: 97chocho
    driver-class-name: com.mysql.cj.jdbc.Driver



