
server:
  port: 8001

spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: create-drop
  show-sql: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/registryservice
    username: postgres
    password: 97chocho
    driver-class-name: org.postgresql.Driver
    database-platform: org.hibernate.dialect.PostgresSQLDialect
